# Lesson 5 - Assignment

In this assignment, you will implement a Support Vector Machine Classifier  from scratch and compare the results to existing sklearn algorithm.

In [6]:
# import packages
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
from matplotlib.legend_handler import HandlerLine2D
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split
from sklearn.utils import shuffle

# make this notebook's output stable across runs
np.random.seed(0)

## Question 1.1: Implement the cost function cost/objective function:
<img src="https://miro.medium.com/max/688/1*JAS6rUTO7TDlrv4XZSMbsA.png" alt="drawing" width="600"/>

The above is a Soft-margin case of SVM in which the data isn't linearly separable. (https://en.wikipedia.org/wiki/Support_vector_machine#Soft-margin)

In [21]:
X

             1        2        3  intercept
0      8.66610  -2.8073 -0.44699          1
1      8.16740  -2.4586 -1.46210          1
2     -2.63830   1.9242  0.10645          1
3      9.52280  -4.0112 -3.59440          1
4     -4.45520   4.5718 -0.98880          1
...        ...      ...      ...        ...
1367   1.34920  -1.4501 -0.55949          1
1368  -4.87730   6.4774  0.34179          1
1369 -13.45860  17.5932 -2.77710          1
1370  -8.38270  12.3930 -1.28230          1
1371  -0.65804   2.6842  1.19520          1

[1372 rows x 4 columns]

In [75]:
def compute_cost(W, X, Y,reg_strength=1000): #implementing (1)/(4)
    # TODO calculate cost function
    N = len(X)
    S = np.sum([])
    sigma = 0
    for i in range(N):
        x_i,y_i = X[i],Y[i] #Removed X.values[i]
        delta = 1 - y_i*(np.dot(W,x_i)) #Except +b is missing.
        sigma += np.max(0,delta)
    cost = (1/2)*np.sum(self.W*self.W) + (reg_strength/N)*sigma 
    return cost

## Question 1.2: Write a method that calculate the cost gradient:
<img src="https://miro.medium.com/max/866/1*ww3F21VMVGp2NKhm0VTesA.png" alt="drawing" width="600"/>

In [65]:
def calculate_cost_gradient(W, X_batch, Y_batch, reg_strength=1000): #implementing (5)
    if type(Y_batch) == np.float64:Y_batch = np.array([Y_batch])
    distance = 1 - (Y_batch * np.dot(X_batch,W))
    dw = np.zeros(len(W))
    #for i, distance in enumerate(distance): #Doesn't work. Returns TypeError: 'numpy.float64' object is not iterable
    for distance in [distance]:
        
        if max(0,distance) == 0:
            d_i = W
        else:
            d_i = W - (reg_strength*Y_batch*X_batch) #removed the [i] that was to the right of Y_batch and X_batch
        dw += distance
    dw = dw#/len(Y_batch)
    return dw

## Question 1.3: Write a method that performs stochastic Gradient descent as follows:
- Caluclate the gradient of cost function i.e. ∇J(w)
- Update the weights in the opposite direction to the gradient: w = w — ∝(∇J(w))
- Repeat until conversion or until 5000 epochs are reached

In [19]:
def sgd(data, outputs, learning_rate = 0.0001, max_epochs = 5000):
    weights = np.zeros(data.shape[1])
    nth = 0
    prev_cost = float('inf')
    cost_threshold = 0.01  # in percent
    # stochastic gradient descent
    for epoch in range(1, max_epochs):
        # shuffle to prevent repeating update cycles
        X, Y = shuffle(data,outputs)
        for ind, x in enumerate(X):
            ascent = calculate_cost_gradient(weights, x, Y[ind])
            weights = weights - (learning_rate * ascent)
            # convergence check on 2^nth epoch
            if epoch == 2 ** nth or epoch == (max_epochs - 1):
                cost = compute_cost(weights, data, outputs)
                print("Epoch is:{} and Cost is: {}".format(epoch, cost))
                # stoppage criterion
                if abs(prev_cost-cost) < cost_threshold*prev_cost:
                    return weights
                prev_cost = cost
                nth +=1
    return weights

# Dataset

In [29]:
data = pd.read_csv('data_banknote_authentication.csv', header=None)

Y = data.iloc[:, -1]  
X = data.iloc[:, 1:4]
#X.insert(loc=len(X.columns), column='intercept', value=1)

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.4, random_state=42)

In [21]:
data.iloc[:, 1:]

             1        2        3  4
0      8.66610  -2.8073 -0.44699  0
1      8.16740  -2.4586 -1.46210  0
2     -2.63830   1.9242  0.10645  0
3      9.52280  -4.0112 -3.59440  0
4     -4.45520   4.5718 -0.98880  0
...        ...      ...      ... ..
1367   1.34920  -1.4501 -0.55949  1
1368  -4.87730   6.4774  0.34179  1
1369 -13.45860  17.5932 -2.77710  1
1370  -8.38270  12.3930 -1.28230  1
1371  -0.65804   2.6842  1.19520  1

[1372 rows x 4 columns]

In [8]:
from random import seed
from random import randrange
from csv import reader

# Load a CSV file
def load_csv(filename):
    file = open(filename, "rt")
    lines = reader(file)
    dataset = list(lines)
    return dataset
 
# Convert string column to float
def str_column_to_float(dataset, column):
    for row in dataset:
        row[column] = row[column].strip()#.astype(float)
        
filename = 'data_banknote_authentication.csv'
dataset = load_csv(filename)
# convert string attributes to integers
for i in range(len(dataset[0])):
    str_column_to_float(dataset, i)
train = dataset[1:np.int(len(dataset)*2/3)]
test = dataset[np.int(len(dataset)*2/3)+1:len(dataset)]

/tmp/ipykernel_7260/2935497740.py:22: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  train = dataset[1:np.int(len(dataset)*2/3)]
/tmp/ipykernel_7260/2935497740.py:23: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  test = dataset[np.int(len(dataset)*2/3)+1:len(dataset)]

## Question 4: Train and evaluate an SVC using the banknote_authentication data

In [ ]:
# train the model
print("training started...")
W = sgd(X_train.to_numpy(), y_train.to_numpy())
print("training finished.")
print("weights are: {}".format(W))

# testing the model on test set
y_test_predicted = []
for i in range(X_test.shape[0]):
    yp = np.sign(np.dot(X_test[i],W)) #model
    y_test_predicted.append(yp)
print("accuracy on test dataset: {}".format(accuracy_score(y_test.to_numpy(), y_test_predicted)))

## [Bonus] Question 5: Train and evaluate an SKLEARN SVC model, and compare the results to your model

## Question 6. Create a new text cell in your Notebook: Complete a 50-100 word summary (or short description of your thinking in applying this week's learning to the solution) of your experience in this assignment. Include:
                                                                      
* What was your incoming experience with this model, if any? 
* What steps you took, what obstacles you encountered.
* How you link this exercise to real-world, machine learning problem-solving. (What steps were missing? What else do you need to learn?) 
> This summary allows your instructor to know how you are doing and allot points for your effort in thinking and planning, and making connections to real-world work.

#### I have no experience with SVC but I was happy to see that it has to do with linear algebra and the idea of a hyperplane because I'm a tutor and I've talked about that concept recently. I enjoy linear algebra so this content is even more interesting to me for it's connection to it. I had to make use of the internet to understand how to complete the code that was given as a headstart and to understand how it should work. I haven't gotten the results I want from it yet but I plan on continuing to improve the code after the deadline.